Fix: 스프링버전에 따른 시큐리티 내부 메소드 적용 변경
K-CHANHO/Filmo pull request #6
Opened 2024-10-19 07:00 UTC by sseungminn

+ setRoles("USER")로 수정

2024-10-20 15:39 UTC, K-CHANHO commented on src/main/java/com/movie/test/common/config/SecurityConfig.java
> +        MvcRequestMatcher.Builder mvc = new MvcRequestMatcher.Builder(introspector);
mvcRequestMatcher로 변경하신 이유를 알 수 있을까요?

2024-10-21 00:43 UTC, sseungminn commented on src/main/java/com/movie/test/common/config/SecurityConfig.java
> +        MvcRequestMatcher.Builder mvc = new MvcRequestMatcher.Builder(introspector);
스프링 시큐리티 3.x 버전 사용하면 path matcher에 어떤 matcher 사용할 것인지 명시를 해야한다고 합니다!

2024-10-21 02:02 UTC, K-CHANHO commented on src/main/java/com/movie/test/common/config/SecurityConfig.java
> +        MvcRequestMatcher.Builder mvc = new MvcRequestMatcher.Builder(introspector);
네 맞습니다! 저희는 MVC는 아니고 rest라 AntPathRequestMatcher 사용중이었습니다.
저번에 PR주실때 빼먹으신 듯 하여 제가 추가했었는데 공유를 안 드렸네요..!

2024-10-21 04:45 UTC, K-CHANHO requested changes
시큐리티 관련 Config 설정은 일단 그대로 유지하겠습니다!

2024-10-21 04:45 UTC, closed without merging